default: &default
  adapter: postgresql
  encoding: unicode
  username: codeboxx
  password: Codeboxx1!
  host: codeboxx-postgresql.cq6zrczewpu2.us-east-1.rds.amazonaws.com
  pool: 5

development:
  <<: *default
  database: Sasha_Marinskiy
