
#
default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: maksymkryvoshlyk
  password:

development:
  <<: *default
  database: Rocket_Elevators_Information_System_development

test:
  <<: *default
  database: Rocket_Elevators_Information_System_test

#
production:
  <<: *default
  database: Rocket_Elevators_Information_System_production
  url:  <%= ENV["DATABASE_PG_URL"] %>
  username: maksymkryvoshlyk
  password: 
