
#
default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: codeboxxmac
  password:

development:
  <<: *default
  database: postgres

test:
  <<: *default
  database: postgres

#
production:
  <<: *default
  database: postgres
  url: <%= ENV["DATABASE_PG_URL"] %>
  username: codeboxxmac
  password: